base:
  applicationName: hello-world
  ingress:
    public: false
    host: "hello-world-staging.lab.com"
    master: true
    paths:
      - /
    secret: nana-systems
  healthCheck:
    path: /
  backend:
    backendtimeout: "90"
    unhealthy: "5"
    interval: "30"
    healthtimeout: "15"
    healthy: "1"
  image:
    repository: dev-nana-295215/hello-world
    registry: us.gcr.io # Optional
    stableTag: latest # Optional
    canaryTag: latest # Optional
  containerPort: 3000
  mountHostPath:
    - name: tz-config
      hostPath: /usr/share/zoneinfo/Asia/Riyadh
      mountPath: /etc/localtime
      type: File
  resources:
    apps:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 256Mi
  apps:
    items:
      app:
        healthcheck_enabled: true
        healthcheck:
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 10
            initialDelaySeconds: 10
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 10
            initialDelaySeconds: 10
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 5
        replicas: 1
        hpa:
          type: default
          min: 1
          max: 2
  enabled:
    apps: true